# Generated by Django 3.0.4 on 2020-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilities',
            name='abilityTitle',
        ),
    ]
