# Generated by Django 3.0.4 on 2020-04-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skillTitle',
        ),
    ]
