# Generated by Django 3.0.4 on 2020-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
